config/routes.rb
Rails.application.routes.draw do
  resources :bikes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "bikes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[ show edit update destroy ]

  # GET /bikes or /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1 or /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes or /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to bike_url(@bike), notice: "Bike was successfully created." }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1 or /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to bike_url(@bike), notice: "Bike was successfully updated." }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1 or /bikes/1.json
  def destroy
    @bike.destroy!

    respond_to do |format|
      format.html { redirect_to bikes_url, notice: "Bike was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bike_params
      params.require(:bike).permit(:brand, :wheels, :usage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_bike.html.erb
<div id="<%= dom_id bike %>">
  <p>
    <strong>Brand:</strong>
    <%= bike.brand %>
  </p>

  <p>
    <strong>Wheels:</strong>
    <%= bike.wheels %>
  </p>

  <p>
    <strong>Usage:</strong>
    <%= bike.usage %>
  </p>

</div>

app/views/bikes/_form.html.erb
<%= form_with(model: bike) do |form| %>
  <% if bike.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
        <% bike.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :wheels, style: "display: block" %>
    <%= form.number_field :wheels %>
  </div>

  <div>
    <%= form.label :usage, style: "display: block" %>
    <%= form.text_field :usage %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing bike</h1>

<%= render "form", bike: @bike %>

<br>

<div>
  <%= link_to "Show this bike", @bike %> |
  <%= link_to "Back to bikes", bikes_path %>
</div>

app/views/bikes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>
  <%= react_component("HelloMartin", { greeting: "Hello from react-rails." }) %>
</h1>

<h1>Bikes</h1>

<div id="bikes">
  <% @bikes.each do |bike| %>
    <%= render bike %>
    <p>
      <%= link_to "Show this bike", bike %>
    </p>
  <% end %>
</div>

<%= link_to "New bike", new_bike_path %>

app/views/bikes/new.html.erb
<h1>New bike</h1>

<%= render "form", bike: @bike %>

<br>

<div>
  <%= link_to "Back to bikes", bikes_path %>
</div>

app/views/bikes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bike %>

<div>
  <%= link_to "Edit this bike", edit_bike_path(@bike) %> |
  <%= link_to "Back to bikes", bikes_path %>

  <%= button_to "Destroy this bike", @bike, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactRailsShakapacker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>